version: 2.1
jobs:
  build_and_publish:
    docker:
      - image: cimg/node:20.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public
  build_only:
    docker:
      - image: cimg/node:20.9.0
    working_directory: ~/repo
    steps:
      - checkout

workflows:
  publish:
    jobs:
      - build_and_publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  build:
    jobs:  
      - build_only:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
